# Generated by Django 4.1.7 on 2023-04-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
