# Generated by Django 4.1.7 on 2023-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMORPG', '0002_alter_ad_options_alter_response_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(to='MMORPG.category'),
        ),
    ]
